config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root 'home#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_type_decorator.rb
Spree::OptionType.class_eval do
  scope :search_with_products_and_presentation, -> (products, presentation) {
    joins(:products).
      where(presentation: presentation, spree_products: { id: products.ids })
  }
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :search_with_products_and_presentation, -> (products, presentation) {
    where(option_type_id: Spree::OptionType.search_with_products_and_presentation(products, presentation).ids)
  }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :order_newest, -> { order(available_on: :desc) }
  scope :order_oldest, -> { order(available_on: :asc) }
  scope :with_master_image_and_price, -> { includes(master: [:images, :default_price]) }
  scope :taxons_relation_products, -> (product) {
    joins(:taxons).where(spree_taxons: { id: product.taxons.ids }).
      where.not(id: product.id).distinct
  }
  scope :has_option_value, -> (value) {
    joins(variants_including_master: :option_values).where(spree_option_values: { id: value.id }).distinct
  }
  scope :reorder_by, -> (order) {
    case order
    when 'price-dsc' then reorder(nil).descend_by_master_price
    when 'price-asc' then reorder(nil).ascend_by_master_price
    when 'oldest'    then reorder(nil).order_oldest
    else reorder(nil).order_newest
    end
  }

  def self.order_option_hash
    {
      "新着順":      'newest',
      "価格の安い順": 'price-asc',
      "価格の高い順": 'price-dsc',
      "古い順":      'oldest',
    }
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  scope :has_option_value, -> (option_value_name) {
    joins(:option_values).where(spree_option_values: { name: option_value_name })
  }
  scope :with_image_and_price, -> { includes(:images, :prices) }
  scope :search_with_products, -> (products) { where(product_id: products.ids) }
  scope :order_descend_by_price, -> { joins(:prices).order("spree_prices.amount DESC") }
  scope :order_ascend_by_price, -> { joins(:prices).order("spree_prices.amount ASC") }
  scope :order_newest_by_product_available_on, -> { joins(:product).order("spree_products.available_on DESC") }
  scope :order_oldest_by_product_available_on, -> { joins(:product).order("spree_products.available_on ASC") }
  scope :order_by, ->(order) {
    case order
    when 'price-dsc' then order_descend_by_price
    when 'price-asc' then order_ascend_by_price
    when 'oldest'    then order_oldest_by_product_available_on
    else order_newest_by_product_available_on
    end
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(:taxons)
    @same_taxon_products = Spree::Product.in_taxon(@taxon)
    @products =
      if params[:color]
        Spree::Variant.
          with_image_and_price.
          search_with_products(@same_taxon_products).
          has_option_value(params[:color]).
          order_by(params[:order]).
          uniq { |variant| variant.product_id }
      else
        @same_taxon_products.with_master_image_and_price.reorder_by(params[:order])
      end

    @color_option_values =
      Spree::OptionValue.
        search_with_products_and_presentation(@same_taxon_products, 'Color').
        uniq
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NEW_PRODUCTS_IN_PAGE = 10
  def index
    @new_products = Spree::Product.with_master_image_and_price.order_newest.limit(MAX_NEW_PRODUCTS_IN_PAGE)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_PRODUCT_SQL = 10
  MAX_RELATION_PRODUCTS_IN_PAGE = 4
  def show
    @product = Spree::Product.find(params[:id])
    @relation_products =
      Spree::Product.
        with_master_image_and_price.
        taxons_relation_products(@product).
        limit(MAX_PRODUCT_SQL).
        sample(MAX_RELATION_PRODUCTS_IN_PAGE)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end

  def cover_all_title(*titles)
    titles.join(" ")
  end
end

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">

  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li>
              <a href="#">
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-dribbble"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-vimeo"></i>
              </a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-tumblr"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li>
              <span>
                <a data-toggle="modal" href='#login'>Log in</a>
                <small>or</small>
                <a data-toggle="modal" href='#signup'>Create an account</a>
              </span>
          　</li>
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-search"></i>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <span class="input-group">
                    <input type="text" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span class="input-group-addon" id="basic-addon2">Search</span>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-shopping-cart"></i>$0</a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>Item(s) in your cart</li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT
                          <br>
                          <span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#">
                    <div class="media">
                      <%= image_tag("img/home/cart-items/cart-item-01.jpg", :class => "media-left media-object", :alt => "cart-Image") %>
                      <div class="media-body">
                        <h5 class="media-heading">INCIDIDUNT UT
                          <br>
                          <span>2 X $199</span></h5>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <div class="btn-group" role="group" aria-label="...">
                    <button type="button" class="btn btn-default">Shopping Cart</button>
                    <button type="button" class="btn btn-default">Checkout</button>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to potepan_root_path, class: "navbar-brand" do %>
          <%= image_tag("img/logo.png", :alt => "") %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="<%= potepan_root_path %>">Home</a>
          </li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li>
                    <a href="product_grid_left_sidebar.html">Products Sidebar Left</a>
                  </li>
                  <li>
                    <a href="product-grid-right-sidebar.html">Products Sidebar Right</a>
                  </li>
                  <li>
                    <a href="product-grid-3-col-filter.html">Products 3 Columns V1</a>
                  </li>
                  <li>
                    <a href="product-grid-3-col.html">Products 3 Columns V2</a>
                  </li>
                  <li>
                    <a href="product-grid-4-col.html">Products 4 Columns</a>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li>
                    <a href="product_list_left_sidebar.html">Products Sidebar Left</a>
                  </li>
                  <li>
                    <a href="product-list-right-sidebar.html">Products Sidebar Right</a>
                  </li>
                  <li class="listHeading">Others</li>
                  <li class="active">
                    <a href="single_product.html">Single Product</a>
                  </li>
                  <li>
                    <a href="cart_page.html">Cart Page</a>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li>
                    <a href="checkout_step_1.html">Step 1 - Address</a>
                  </li>
                  <li>
                    <a href="checkout_step_2.html">Step 2 - Shipping</a>
                  </li>
                  <li>
                    <a href="checkout_step_3.html">Step 3 - Payment</a>
                  </li>
                  <li>
                    <a href="checkout_step_4.html">Step 4 - Payment</a>
                  </li>
                  <li>
                    <a href="checkout_complete.html">Order Complete</a>
                  </li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">pages</a>
            <ul class="dropdown-menu dropdown-menu-left">
              <li>
                <a href="about_us.html">About Us</a>
              </li>
              <li>
                <a href="signup.html">Register</a>
              </li>
              <li>
                <a href="signup-login.html">Register or Login</a>
              </li>
              <li>
                <a href="login.html">Login</a>
              </li>
              <li>
                <a href="lost-password.html">Password Recovery</a>
              </li>
              <li>
                <a href="privacy_policy.html">Privacy Policy</a>
              </li>
              <li>
                <a href="terms-and-conditions.html">Terms &amp; Conditions</a>
              </li>
              <li>
                <a href="404.html">404 Not Found</a>
              </li>
              <li>
                <a href="coming-soon.html">Coming Soon</a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">blog</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <a href="blog_right_sidebar.html">Right Sidebar</a>
              </li>
              <li>
                <a href="blog_left_sidebar.html">Left Sidebar</a>
              </li>
              <li>
                <a href="blog-fullwidth.html">Full Width</a>
              </li>
              <li>
                <a href="blog-single-fullwidth.html">Single Post</a>
              </li>
              <li>
                <a href="blog_single_right_sidebar.html">Single Right Sidebar</a>
              </li>
              <li>
                <a href="blog_single_left_sidebar.html">Single Left Sidebar</a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li>
                <a href="account-dashboard.html">Dashboard</a>
              </li>
              <li>
                <a href="account-profile.html">Profile</a>
              </li>
              <li>
                <a href="account-all-orders.html">All Orders</a>
              </li>
              <li>
                <a href="account-single-order.html">Single Order</a>
              </li>
              <li>
                <a href="account-wishlist.html">Wishlist</a>
              </li>
              <li>
                <a href="account-address.html">Address</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  </nav>

</div>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- PORDUCT QUICK VIEW MODAL -->
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("img/products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>$149</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">Size</option>
                <option value="1">Size 1</option>
                <option value="2">Size 2</option>
                <option value="3">Size 3</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="0">Qty</option>
                <option value="1">Qty 1</option>
                <option value="2">Qty 2</option>
                <option value="3">Qty 3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="#" class="btn btn-primary btn-block">Add to cart
                <i class="fa fa-angle-right" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_order_pulldown.html.erb
<div class="col-xs-6">
  <%= form_tag(potepan_category_path(params[:id]), method: :get) do %>
    <%= select_tag 'order', options_for_select(Spree::Product.order_option_hash, selected: params[:order] || 'newest'), { class: "select-drop", onChange: "this.form.submit()" } %>
    <%= hidden_field_tag :layout, params[:layout]  if params[:layout] %>
    <%= hidden_field_tag :color, params[:color] if params[:color] %>
  <% end %>
</div>

app/views/potepan/categories/_product.html.erb
<% if params[:layout] == "list" %>
  <div class="col-xs-12">
    <div class="media">
      <div class="media-left">
        <%= image_tag(product.images.first.attachment(:product), :class => "media-object", :alt => "Image") %>
        <span class="maskingImage">
          <a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a>
        </span>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to potepan_product_path(product.kind_of?(Spree::Variant) ? product.product_id : product.id) do %>
            <h5><%= product.name %></h5>
          <% end %>
        </h4>
        <p><%= product.description %></p>
        <h3><%= product.display_price %></h3>
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal">
            <i class="fa fa-heart" aria-hidden="true"></i>
          </button>
          <button type="button" class="btn btn-default" onclick="location.href='cart-page.html';">
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="col-sm-4 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.images.first.attachment(:product), :alt => "products-img") %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li>
              <a data-toggle="modal" href=".login-modal" class="btn btn-default">
                <i class="fa fa-heart"></i>
              </a>
            </li>
            <li>
              <a href="cart_page.html" class="btn btn-default">
                <i class="fa fa-shopping-cart"></i>
              </a>
            </li>
            <li>
              <a class="btn btn-default" data-toggle="modal" href=".quick-view">
                <i class="fa fa-eye"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <%= link_to potepan_product_path(product.kind_of?(Spree::Variant) ? product.product_id : product.id) do %>
          <h5><%= product.name %></h5>
        <% end %>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/categories/filter/_category_filter.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% @taxonomies.each do |taxnomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxnomy.id %>"><%= taxnomy.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="<%= taxnomy.id %>" class="collapse collapseItem">
              <% taxnomy.taxons.each do |taxon| %>
                <% next if taxon.root? %>
                  <li>
                    <%= link_to potepan_category_path(taxon.id) do %>
                      <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %>
                      <span>(<%= Spree::Product.in_taxon(taxon).count %>)</span>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/filter/_color_filter.html.erb
<% if @color_option_values.any? %>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
    <% @color_option_values.each do |color| %>
      <li>
        <%= link_to potepan_category_path(params[:id], color: "#{color.name}") do %>
          <%= color.name %>
          <span>(<%= @same_taxon_products.has_option_value(color).count %>)</span>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/potepan/categories/show.html.erb
<% provide(:title, cover_all_title(@taxon.name, params[:color])) %>
<%= render 'potepan/shared/light_section' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <%= render 'sidebar' %>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <%= render 'order_pulldown' %>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default <%= !params.key?(:layout) || params[:layout] == "grid" ? "active" : ''%>" onclick= "window.location.href= '<%= potepan_category_path(params[:id], layout: "grid", color: params[:color], order: params[:order])%>'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default <%=  params[:layout] == "list" ? "active" : ''%>" onclick="window.location.href= '<%= potepan_category_path(params[:id], layout: "list", color: params[:color], order: params[:order])%>'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row <%= params[:layout] == "list" ? "productListSingle" : "" %>">
          <%= render partial: 'potepan/categories/product', collection: @products %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/partners_logo_slider'%>

app/views/potepan/home/_new_product.html.erb
<div class="slide">
  <div class="productImage <%= new_product == @new_products.first ? "clearfix" : "" %>">
    <%= image_tag(new_product.images.first.attachment(:product), :alt => "featured-product-img") %>
    <div class="productMasking">
      <ul class="list-inline btn-group" role="group">
        <li>
          <a data-toggle="modal" href=".login-modal" class="btn btn-default">
            <i class="fa fa-heart"></i>
          </a>
        </li>
        <li>
          <a href="cart_page.html" class="btn btn-default">
            <i class="fa fa-shopping-cart"></i>
          </a>
        </li>
        <li>
          <a data-toggle="modal" href=".quick-view" class="btn btn-default">
            <i class="fa fa-eye"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
  <div class="productCaption clearfix">
    <%= link_to potepan_product_path(new_product.id) do %>
      <h5><%= new_product.name %></h5>
    <% end %>
    <h3><%= new_product.display_price %></h3>
  </div>
</div>

app/views/potepan/products/_relation_product.html.erb
<div class="col-md-3 col-sm-6 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(relation_product.images.first.attachment(:product), :alt => "products-img") %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(relation_product.id) do %>
        <h5><%= relation_product.name %></h5>
      <% end %>
      <h3><%= relation_product.display_price %></h3>
    </div>
  </div>
</div>

app/views/potepan/shared/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= yield(:title) %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'HOME', potepan_root_path%>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= yield(:title) %></li>
        </ol>
      </div>
    </div>
  </div>
</section>